version: '3'
services:
  mongo:
    image: mongo:4.2
    container_name: "mongo-db"
    restart: always
    ports:
      - "27017:27017"
  app:
    image: spring-reactive-web-mongodb:latest
    container_name: "spring-reactive-rest-api"
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mongo
    ports:
      - 8082:8082